<<<<<<< HEAD
import type { Metadata } from 'next'
=======
<<<<<<< HEAD
>>>>>>> 5afa943 (fresh start)
import './globals.css'
import { AppProviders } from '@/components/app-providers'
import { AppLayout } from '@/components/app-layout'
import React from 'react'

<<<<<<< HEAD
export const metadata: Metadata = {
  title: 'Placeholder',
=======
export const metadata = {
  title: 'VotingSystemSolana',
=======
import type { Metadata } from 'next'
import './globals.css'
import { AppProviders } from '@/components/app-providers'
import { AppLayout } from '@/components/app-layout'
import React from 'react'

export const metadata: Metadata = {
  title: 'Placeholder',
>>>>>>> 8e1c1dc (chore: initial commit)
>>>>>>> 5afa943 (fresh start)
  description: 'Generated by create-solana-dapp',
}

const links: { label: string; path: string }[] = [
<<<<<<< HEAD
  // More links...
  { label: 'Home', path: '/' },
=======
<<<<<<< HEAD
>>>>>>> 5afa943 (fresh start)
  { label: 'Account', path: '/account' },
  { label: 'Counter Program', path: '/counter' },
]

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
<<<<<<< HEAD
=======
    <html lang="en">
      <body>
        <ReactQueryProvider>
          <ClusterProvider>
            <SolanaProvider>
              <UiLayout links={links}>{children}</UiLayout>
            </SolanaProvider>
          </ClusterProvider>
        </ReactQueryProvider>
=======
  // More links...
  { label: 'Home', path: '/' },
  { label: 'Account', path: '/account' },
  { label: 'Counter Program', path: '/counter' },
]

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
>>>>>>> 5afa943 (fresh start)
    <html lang="en" suppressHydrationWarning>
      <body className={`antialiased`}>
        <AppProviders>
          <AppLayout links={links}>{children}</AppLayout>
        </AppProviders>
<<<<<<< HEAD
=======
>>>>>>> 8e1c1dc (chore: initial commit)
>>>>>>> 5afa943 (fresh start)
      </body>
    </html>
  )
}
<<<<<<< HEAD
=======
<<<<<<< HEAD
=======
>>>>>>> 5afa943 (fresh start)
// Patch BigInt so we can log it using JSON.stringify without any errors
declare global {
  interface BigInt {
    toJSON(): string
  }
}

BigInt.prototype.toJSON = function () {
  return this.toString()
}
<<<<<<< HEAD
=======
>>>>>>> 8e1c1dc (chore: initial commit)
>>>>>>> 5afa943 (fresh start)
