[toolchain]
<<<<<<< HEAD
package_manager = "yarn"
=======
<<<<<<< HEAD
anchor_version = "0.30.1"
=======
package_manager = "yarn"
>>>>>>> 8e1c1dc (chore: initial commit)
>>>>>>> 5afa943 (fresh start)

[features]
resolution = true
skip-lint = false

[programs.localnet]
<<<<<<< HEAD
counter = "FqzkXZdwYjurnUKetJCAvaUw5WAqbwzU6gZEwydeEfqS"
=======
<<<<<<< HEAD
VotingSystemSolana = "coUnmi3oBUtwtd9fjeAvSsJssXh5A5xyPbhpewyzRVF"
=======
counter = "FqzkXZdwYjurnUKetJCAvaUw5WAqbwzU6gZEwydeEfqS"
>>>>>>> 8e1c1dc (chore: initial commit)
>>>>>>> 5afa943 (fresh start)

[registry]
url = "https://api.apr.dev"

[provider]
<<<<<<< HEAD
cluster = "localnet"
=======
<<<<<<< HEAD
cluster = "Localnet"
=======
cluster = "localnet"
>>>>>>> 8e1c1dc (chore: initial commit)
>>>>>>> 5afa943 (fresh start)
wallet = "~/.config/solana/id.json"

[scripts]
test = "../node_modules/.bin/jest --preset ts-jest"
<<<<<<< HEAD
=======
<<<<<<< HEAD

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[test.validator]
bind_address = "127.0.0.1"
ledger = ".anchor/test-ledger"
rpc_port = 8899
=======
>>>>>>> 8e1c1dc (chore: initial commit)
>>>>>>> 5afa943 (fresh start)
